### ISSUE TITLE
v0.3.0 release checklist

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-auditable#49]
- [x] Update repository URL in Cargo.toml files
- [x] Remove all references to `auditable` crate and replace then with `cargo auditable`
- [x] Create a test to check rlib and bin in a single crate to fulfill [this TODO](https://github.com/rust-secure-code/cargo-auditable/blob/44bb83b00fa17dd538de6a5c354f3b648e503c5b/cargo-auditable/src/rustc_wrapper.rs#L16-L17)
- [x] Figure out how to make Cargo publish the toplevel README.md to crates.io under the `cargo auditable` package
- [ ] ~~#52~~
